# Generated by Django 5.1.5 on 2025-02-27 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='load_approve',
            new_name='loan_approve',
        ),
    ]
