# Generated by Django 5.1.5 on 2025-02-03 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_student_father_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='adderess',
            new_name='address',
        ),
    ]
