# Generated by Django 5.1.5 on 2025-02-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelForm', '0003_mymodel_generic_ip_address_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='null_boolean_field',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='json_field',
            field=models.JSONField(default=dict),
        ),
    ]
