# Generated by Django 5.1.5 on 2025-02-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelForm', '0004_mymodel_null_boolean_field_alter_mymodel_json_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='positive_big_integer_field',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='positive_integer_field',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='positive_small_integer_field',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
