# Generated by Django 5.1.5 on 2025-02-07 10:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelForm', '0005_mymodel_positive_big_integer_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='slug_field',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='small_integer_field',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='url_field',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='uuid_field',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
