# Generated by Django 5.1.5 on 2025-02-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelForm', '0006_mymodel_slug_field_mymodel_small_integer_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='generic_ip_address_field',
            field=models.GenericIPAddressField(blank=True, default='none', null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='json_field',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='url_field',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
