# Generated by Django 5.1.5 on 2025-02-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelForm', '0007_alter_mymodel_generic_ip_address_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='generic_ip_address_field',
            field=models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True),
        ),
    ]
