# Generated by Django 5.1.5 on 2025-02-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_imaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imaga',
            field=models.ImageField(blank=True, null=True, upload_to='posts/media/uploads/'),
        ),
    ]
